version: '3.1'

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - 9090:80
    volumes:
      - .:/var/www

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    ports:
      - 3307:3306
