version: '3.1'

networks:
  karting: {}

services:
  app:
    image: mtk3d/php:8.0-fpm-nginx
    ports:
      - 9090:80
    volumes:
      - .:/var/www
    networks:
      - karting

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    ports:
      - 3307:3306
    networks:
      - karting
