version: '3.1'

services:
  app:
    build:
      context: ./
      dockerfile: .docker/php/Dockerfile
    ports:
      - 9090:80
    volumes:
      - .:/var/www

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3307:3306
